# Generated by Django 2.2.4 on 2019-09-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('horario', models.DateTimeField()),
                ('local', models.TextField()),
            ],
        ),
    ]
