# Generated by Django 2.2.5 on 2019-09-05 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compromisso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField()),
                ('fk_observacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compromisso.Compromisso')),
            ],
        ),
    ]
